config/routes.rb
Rails.application.routes.draw do

  post 	'login'	     =>	'sessions#create'
  delete 'logout'	     =>	'sessions#destroy'
  get       'login'	     =>	'sessions#new'
  get       'signup'     =>	'users#new'
  get       'help' 	     =>	'static_pages#help'
  get       'about'      =>	'static_pages#about'
  get       'contact'    =>	'static_pages#contact'

  root 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts,		only: [ :create, :destroy]
  resources :relationships,    only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		The
		<a href="http://www.izhanghan.com/">qulook.com</a>
		by
		<a href="http://www.izhanghan.com">zhang han @2015</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "关于",		about_path %></li>
			<li><%= link_to "联系我们",	contact_path %></li>
			<li><a href="http://www.izhanghan.com/"></a>@2015-2025</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "鲁克微博", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
			<% if logged_in? %>
				<li><%= link_to "发微博",	root_path %></li>
			<% else %>
				<li><%= link_to "主页",	root_path %></li>
			<% end %>
				<li><%= link_to "帮助",	help_path %></li>
				<!-- 用户模块和非用户模块 -->
				<% if logged_in? %>
					<li><%= link_to "用户列表", users_path %></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<%= current_user.name %> <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to "我的主页", current_user %></li>
							<li><%= link_to "设置", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li><%= link_to "登出", logout_path, method: "delete" %></li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "注册微博",signup_path %></li>
					<li><%= link_to "登陆", login_path %></li>
				<% end %></ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<!-- 消息提示 -->
		<% flash.each do |message_type, message| %>
			<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
			<!--  <div class="alert alert-<%= message_type %>"><%= message %></div>	-->
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>	
</html>